# Generated by Django 4.0.3 on 2022-03-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prettynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='mboile',
            new_name='mobile',
        ),
    ]
